typography_spectrum: 0.48781
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#b7b7b7'
    - '#484848'
    - '#676767'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49706
analytics:
  google: null
  facebook: null
  twitter: null
name: MatCoker
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'This Site Makes Me Want to Cry :('
description: But it's getting better!
purpose: []
