name: MatCoker
favicon: null
layout_spectrum: 0.7579
typography_spectrum: 0.93767
title: 'This Site Makes Me Want to Cry :('
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#b7b7b7'
    - '#484848'
    - '#676767'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
